#!/usr/bin/dh-exec
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsGbmSupport/QtEglFsKmsGbmSupport
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsGbmSupport/QtEglFsKmsGbmSupportDepends
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsGbmSupport/QtEglFsKmsGbmSupportVersion
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsGbmSupport/qteglfskmsgbmsupportversion.h
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsSupport/QtEglFsKmsSupport
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsSupport/QtEglFsKmsSupportDepends
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsSupport/QtEglFsKmsSupportVersion
[linux-any] usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFsKmsSupport/qteglfskmssupportversion.h
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateAdditionalTargetInfo.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateConfig.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateConfigVersion.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateConfigVersionImpl.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateDependencies.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateTargets-none.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsGbmSupportPrivate/Qt6EglFsKmsGbmSupportPrivateVersionlessTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateAdditionalTargetInfo.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateConfig.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateConfigVersion.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateConfigVersionImpl.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateDependencies.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateTargets-none.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFsKmsSupportPrivate/Qt6EglFsKmsSupportPrivateVersionlessTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginAdditionalTargetInfo.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginConfig.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginConfigVersion.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginConfigVersionImpl.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginTargets-none.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsEglDeviceIntegrationPluginTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginAdditionalTargetInfo.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginConfig.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginConfigVersion.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginConfigVersionImpl.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginTargets-none.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6Gui/Qt6QEglFSKmsGbmIntegrationPluginTargets.cmake
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFsKmsGbmSupport.prl
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFsKmsGbmSupport.so
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFsKmsSupport.prl
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFsKmsSupport.so
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/metatypes/qt6eglfskmsgbmsupportprivate_none_metatypes.json
[linux-any] usr/lib/${DEB_HOST_MULTIARCH}/metatypes/qt6eglfskmssupportprivate_none_metatypes.json
[linux-any] usr/share/qt6/modules/EglFsKmsGbmSupportPrivate.json
[linux-any] usr/share/qt6/modules/EglFsKmsSupportPrivate.json
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFSDeviceIntegration/QtEglFSDeviceIntegration
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFSDeviceIntegration/QtEglFSDeviceIntegrationDepends
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFSDeviceIntegration/QtEglFSDeviceIntegrationVersion
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtEglFSDeviceIntegration/qteglfsdeviceintegrationversion.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLBuffer
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLDebugLogger
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLDebugMessage
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFramebufferObject
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFramebufferObjectFormat
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_0
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_1
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_2
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_3
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_4
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_1_5
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_2_0
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_2_1
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_0
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_1
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_2_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_2_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_3_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_3_3_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_0_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_0_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_1_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_1_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_2_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_2_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_3_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_3_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_4_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_4_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_5_Compatibility
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_4_5_Core
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLFunctions_ES2
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLPaintDevice
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLPixelTransferOptions
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLShader
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLShaderProgram
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLTexture
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLTextureBlitter
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLTimeMonitor
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLTimerQuery
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLVersionFunctions
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLVersionFunctionsFactory
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLVersionProfile
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLVertexArrayObject
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QOpenGLWindow
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QtOpenGL
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QtOpenGLDepends
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/QtOpenGLVersion
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglbuffer.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopengldebug.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglframebufferobject.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_0.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_1.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_2.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_3.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_4.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_1_5.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_2_0.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_2_1.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_0.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_1.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_2_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_2_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_3_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_3_3_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_0_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_0_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_1_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_1_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_2_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_2_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_3_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_3_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_4_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_4_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_5_compatibility.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_4_5_core.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglfunctions_es2.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglpaintdevice.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglpixeltransferoptions.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglshaderprogram.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopengltexture.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopengltextureblitter.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopengltimerquery.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglversionfunctions.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglversionfunctionsfactory.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglversionprofile.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglvertexarrayobject.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qopenglwindow.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qtopenglglobal.h
usr/include/${DEB_HOST_MULTIARCH}/qt6/QtOpenGL/qtopenglversion.h
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateAdditionalTargetInfo.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateConfig.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateConfigVersion.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateConfigVersionImpl.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateDependencies.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateTargets-none.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateTargets.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6EglFSDeviceIntegrationPrivate/Qt6EglFSDeviceIntegrationPrivateVersionlessTargets.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLAdditionalTargetInfo.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLConfig.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLConfigVersion.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLDependencies.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLTargets-none.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLTargets.cmake
usr/lib/${DEB_HOST_MULTIARCH}/cmake/Qt6OpenGL/Qt6OpenGLVersionlessTargets.cmake
usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFSDeviceIntegration.prl
usr/lib/${DEB_HOST_MULTIARCH}/libQt6EglFSDeviceIntegration.so
usr/lib/${DEB_HOST_MULTIARCH}/libQt6OpenGL.prl
usr/lib/${DEB_HOST_MULTIARCH}/libQt6OpenGL.so
usr/lib/${DEB_HOST_MULTIARCH}/metatypes/qt6eglfsdeviceintegrationprivate_none_metatypes.json
usr/lib/${DEB_HOST_MULTIARCH}/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri
usr/lib/${DEB_HOST_MULTIARCH}/qt6/mkspecs/modules/qt_lib_opengl.pri
usr/share/qt6/modules/EglFSDeviceIntegrationPrivate.json
